project:
  type: book

book:
  title: "Australian ecosystems synthesis pipeline"
  subtitle: "Ecosystem Indicator Workflow"
  author: JR Ferrer-Paris
  chapters:
    - index.qmd
    - part: "Catalogue"
      chapters: 
      - catalogue/QLD-REDD.ipynb
    - part: "Crossreferencing"
      chapters: 
      - xref-matrix/QLD-REDD.ipynb
    - part: "Examples"
      chapters: 
      - examples/QLD-T1_1.ipynb
    - Instructions.qmd
    - references.qmd
  margin-header: |
    <center>
    ![](/assets/logo_CES.png){height=66px}
    </center>
  page-footer:
    left: "This site prepared by: [EIW project team](https://github.com/Ecosystem-Indicators-Workflows)"
    center: "![](/assets/unsw_new_logo.png){height=20px} We acknowledge the Bedegal and Gadigal peoples who are the Traditional Owners of the lands where UNSW Sydney is located. We pay our respects to Elders past and present."

bibliography: references.bib

format:
  html:
    theme: minty
    css: styles.css
    highlight-style: solarized
    toc: true
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png